import type { SyncServiceOptions } from './types';
export declare const cleanRoomId: (roomId: string) => string;
export declare class SyncService {
    private options;
    private ws;
    private roomId;
    private isHost;
    private lastMessageId;
    private isSyncing;
    private isProcessing;
    private messageQueue;
    private instanceId;
    private hasSentInitialSync;
    private mergedExcludeIds;
    constructor(options: SyncServiceOptions);
    private setStatus;
    initialize(roomId: string): Promise<string>;
    private analyzeSyncData;
    connect(targetRoomId: string): Promise<void>;
    private connectRelay;
    private processQueue;
    private handleRelayMessage;
    syncData(): Promise<void>;
    private sendRelayAttachment;
    private sendRelayMessage;
    private downloadAndProcessAttachment;
    private processReceivedEncodedData;
    private updateSyncInfoMeta;
    destroy(): void;
}
